### ISSUE TITLE
Feature Request: Share Bookmarklet

### ISSUE THREAD

**Issue by trusz** [Blumed/make-bookmarklets#20]
Hello there!

I really like your site. It is such an easy way to create bookmarklets.

There is just one thing that I am missing. It would be so nice to share bookmarklets as an URL.
Do you think it would be possible to mirror the content of the text area into the URL so we can just copy it and send it to others?

**Comment by Blumed** [comment]
Hello @trusz ! It makes me happy you are enjoying the site. If you have any bookmarklets you want to share I am currently starting a library of bookmarklets I have made and hopefully some contributions from people who use the site.

How would you share the url? Social media? or just people you know?

As far as sharing goes I had the idea when I was creating the site and even implemented it. I sat on the branch for a while, but ultimately I decided not to follow through with it. The main reason is branding. I want this to be a place for people to come and make stuff. If I create the URL with a bookmarklet in it there is nothing stopping people from doing things nefarious in the bookmarklet or sharing someone else's creation which they tampered with. The site would be associated with risk which I do not want to happen. Currently I can guarantee the bookmarklets I share are safe. People creating bookmarklets make them at their own risk and hopefully they make them from scratch without relying on scripts they don't understand or are not in control of. Hopefully I don't sound too paranoid.

If you are thinking about sharing bookmarklets on social media with a long url with javascript in it I don't know if people would be comfortable clicking it. I know I personally wouldn't. The only way I could see people trusting a long large complicated url like that is if you tell people how the url works, which I think you probably have to do for every post and even so I don't know if people would click it. I think a lot of people are trained to be skeptical of urls with code in them, and I think that is probably a good thing.

I hope you understand my position. If you have a way to harden a free to share URL which contains JavaScript and ensure no one can tamper with it. Additionally a url which is not a bazillion character of none human readable text I am all for it and I will implement it.

Currently you can copy the script which is shareable. You could download your script into a file which you could share. You can even make your script in gist and share that which is probably the best way to share bookmarklets on a social network since the script doesn't execute and they can visit the gist and look at how it was made before they decide to use the site's gist bookmarklet maker. 

True if you store a bookmarklet in a url and they come to the site then it would be visible to them in the editor and they could read through it before clicking the create button and moving it into their bookmark bar which is basically the same thing as the gist flow.... I guess it is the fact that there is an extra step of receiving the gist url and looking at it in github which makes me feel like there is more intent from the user. For me if I received a gist url which contains a bookmarklet I would look it over and I would expect some history as it was built and saved which would also give me a bit more confidence in the code. Yes, you could share a gist bookmarklet around which could also end up harmful because someone put something bad in it after people started sharing it and adopting it ( Just like many chrome extensions these days ), but again my url isn't directly associated with it. I know it is a thin line.... but I feel more comfortable with that line I guess because the code lives somewhere else and associated with github and not my site 🤷 

Trust me I love the idea and it would for sure drive more traffic to my site but I just don't want to be associated directly with my URL with scripts that could harm people and I don't see a way of controlling it.

Let me know your thoughts,

Cullan

**Comment by trusz** [comment]
Hi!

I totally get your point.
Thank you for your lengthy answer.
